//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace festivo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public int CouponID { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
        public Nullable<int> EventID { get; set; }
        public string status { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
